# Generated by Django 3.2.3 on 2021-05-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'template categories',
            },
        ),
        migrations.CreateModel(
            name='TemplateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('template_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_objects', to='template_app.templatecategory')),
            ],
        ),
    ]
